# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes Senegal
email: gazettes@codeforafrica.org
url: http://senegal.opengazettes.co
jurisdiction: Senegal
jurisdiction_adjective: Senegalese
jurisdiction_code: SN
source_attribution: Republic Du Senegal Journal Officiel
source_attribution_link: http://www.jo.gouv.sn/spip.php
enforce_ssl: senegal.opengazettes.co
baseurl:
description: Making Government Gazettes freely available.
twitter:
  username: code4africa

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  gazettes:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner_5.png

# Build settings
markdown: kramdown
exclude: [vendor] 

google_analytics: UA-100279361-2

aleph_url: https://search.opengazettes.or.ke/documents2
s3_url: http://senegal.opengazettes.co.s3-website-eu-west-1.amazonaws.com/

